base-url: /data

spring:
  application:
    name: fundAssetsData

  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: "off"