server:
  port: 5001

base-url: /data

spring:
  application:
    name: fundAssetsData

  jpa:
    hibernate:
      ddl-auto: create-drop

springdoc:
  swagger-ui:
    path: /swagger.html

logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: "off"