spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  output:
    ansi:
      enabled: ALWAYS

  liquibase:
    enabled: false